import Navbar from "@/components/navbar/Navbar";
import Provider from "@/components/theme-provider";

import "./globals.css";

export const metadata = {
  title: "SportsHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[#F7F7F8] dark:bg-[#292B32]">
        <Provider>
          <Navbar />
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
